/**
 * @file	leds_management.c
 * @brief  	Functions to control the states of the leds. It is the module used to control the leds.
 * 			If one tries to set a led outside of this module, it will probably not work as intended, as
 * 			this module updates the states of the leds.
 * 			Reads the events generated by the other modules in order to decide what to do with the leds
 * 
 * @written by  	Eliot Ferragni
 * @creation date	10.06.2020
 */

#ifndef LEDS_MANAGEMENT_H
#define LEDS_MANAGEMENT_H


#define BLINK_TIME					100	//used when the target is running or when the robot is in low power state
#define COMMUNICATION_BLINK_TIME	10	//used when a communication is active

/**
* Starts the leds management thread
* Manages the red green and blue leds.
*/
void ledsManagementStart(void);

#endif  /* LEDS_MANAGEMENT_H */